---
- name: Ensure that the {{ appzapper_package }} package is installed
  tags: appzapper
  homebrew_cask:
    name: "{{ appzapper_package|lower }}"
    state: present
  register: appzapper_homebrew_cask

- name: Attempting to apply {{ appzapper_package }} configurations
  tags: appzapper
  osx_defaults:
    domain: "{{ appzapper_domain }}"
    key: "{{ item.key|regex_replace('_', ' ') }}"
    state: "{{ item.value.state|default('present') }}"
    type: "{{ item.value.type }}"
    value: "{{ item.value.value }}"
  with_dict: "{{ appzapper_defaults }}"
  when:
    - item.key is defined
    - item.value.type is defined
    - item.value.value is defined
    - appzapper_defaults|length > 0
    - appzapper_homebrew_cask is success
...
