---
- name: Ensure that the appzapper package is installed
  tags: appzapper
  homebrew_cask:
    name: "{{ appzapper_pkg|lower }}"
    state: present
  register: appzapper_homebrew_cask
  when: appzapper_pkg is defined

- name: Applying appzapper configurations
  tags: appzapper
  osx_defaults:
    domain: "{{ appzapper_domain }}"
    key: "{{ item.key|regex_replace('_', ' ') }}"
    state: "{{ item.value.state|default('present') }}"
    type: "{{ item.value.type }}"
    value: "{{ item.value.value }}"
  with_dict: "{{ appzapper_plist }}"
  when:
    - appzapper_domain is defined
    - item.key is defined
    - item.value.type is defined
    - item.value.value is defined
    - appzapper_homebrew_cask|success
...
